package com.data_management;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * Implements the {@link DataReader} interface to read patient data from
 * text files generated by the {@code FileOutputStrategy}.
 * Each file in the specified directory is parsed line by line.
 * Expected line format:
 * {@code Patient ID: <id>, Timestamp: <ts>, Label: <label>, Data: <value>}
 */
public class FileDataReader implements DataReader {

    private String directory;

    /**
     * Constructs a {@code FileDataReader} that reads from the given directory.
     *
     * @param directory the path to the directory containing patient data files
     */
    public FileDataReader(String directory) {
        this.directory = directory;
    }

    /**
     * Reads all {@code .txt} files in the configured directory and stores
     * the parsed records into the provided {@link DataStorage}.
     * Malformed lines are skipped with a warning printed to stderr.
     *
     * @param dataStorage the storage object where parsed records will be saved
     * @throws IOException if the directory does not exist or cannot be read
     */
    @Override
    public void readData(DataStorage dataStorage) throws IOException {
        Path dirPath = Paths.get(directory);
        if (!Files.exists(dirPath) || !Files.isDirectory(dirPath)) {
            throw new IOException("Directory not found or is not a directory: " + directory);
        }

        Files.list(dirPath)
                .filter(p -> p.toString().endsWith(".txt"))
                .forEach(file -> {
                    try {
                        parseFile(file, dataStorage);
                    } catch (IOException e) {
                        System.err.println("Error reading file: " + file + " - " + e.getMessage());
                    }
                });
    }

    /**
     * Reads and parses all lines of a single file into the data storage.
     *
     * @param file        the path to the file to parse
     * @param dataStorage the storage object to insert records into
     * @throws IOException if the file cannot be opened or read
     */
    private void parseFile(Path file, DataStorage dataStorage) throws IOException {
        try (BufferedReader reader = new BufferedReader(new FileReader(file.toFile()))) {
            String line;
            while ((line = reader.readLine()) != null) {
                parseLine(line.trim(), dataStorage);
            }
        }
    }

    /**
     * Parses a single line of patient data and inserts it into the storage.
     * Lines that do not match the expected format are skipped.
     *
     * @param line        the raw line of text to parse
     * @param dataStorage the storage object to insert the parsed record into
     */
    private void parseLine(String line, DataStorage dataStorage) {
        if (line.isEmpty()) return;
        try {
            // Format: Patient ID: 1, Timestamp: 1714376789050, Label: Saturation, Data: 98.0%
            String[] parts = line.split(", ");
            int patientId = Integer.parseInt(parts[0].replace("Patient ID: ", "").trim());
            long timestamp = Long.parseLong(parts[1].replace("Timestamp: ", "").trim());
            String label = parts[2].replace("Label: ", "").trim();
            // Strip any trailing % sign from saturation values
            String dataStr = parts[3].replace("Data: ", "").replace("%", "").trim();
            double value = Double.parseDouble(dataStr);
            dataStorage.addPatientData(patientId, value, label, timestamp);
        } catch (Exception e) {
            System.err.println("Skipping malformed line: [" + line + "] - " + e.getMessage());
        }
    }
}
